# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'walnut' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for walnut

  target 'walnut-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'walnutTests' do
    inherit! :search_paths
    # Pods for testing
  end

  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.9.0'
  pod 'Firebase/RemoteConfig', '~> 5.9.0'
end

